### ISSUE TITLE
Writing large file stuck in retry

### ISSUE THREAD

**Issue by waiyip-aquabyte** [liormizr/s3path#39] opened 2020-09-03 16:07 UTC
```
>>> p = S3Path("/foo/bar")

This works

>>> with p.open('w') as fp:
...   json.dump([None]*10,fp)


This get stuck for a long time

>>> with p.open('w') as fp:
...   json.dump([None]*5000,fp)


This works well also

>>> p.write_text(json.dumps([None]*5000))

```

When it is stuck, I've seen a lot of log messages like this.
```
DEBUG:urllib3.util.retry:Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
DEBUG:botocore.awsrequest:Waiting for 100 Continue response.
DEBUG:botocore.awsrequest:100 Continue response seen, now sending request body.
```

This looks like an infinite loop. But after a long time, it completed successfully.

**Comment by liormizr** [comment] 2020-09-17 09:57
Hi @waiyip-aquabyte 

I don't see the issue reproducing in me setup with my aws account

It's sound's like a AWS network issue or a boto3 connection issue.

Are you still seeing it reproducing?
Maybe can you see in cloudWatch if s3 network load is high?

About S3Path it's almost the same running:
```
>>> with p.open('w') as fp:
...   json.dump([None]*5000,fp)
```
AND
```
>>> p.write_text(json.dumps([None]*5000))
```

I don't see way it can behave differently.

**Comment by liormizr** [comment] 2020-10-06 07:55
@waiyip-aquabyte are you still seeing the issue?

**Comment by liormizr** [comment] 2020-12-07 07:32
@waiyip-aquabyte are you still seeing the issue?
Or can we close this issue?

**Comment by waiyip-aquabyte** [comment] 2020-12-10 18:30
Sorry, I need find a chance to upgrade and verify. The problem was reproducible.

**Comment by liormizr** [comment] 2020-12-10 19:17
We already start to talk about this issue in a deferent issue #55

@impredicative you talked about your use case
When you are using S3Path and `smart_open`.

Maybe we can use `smart_open` instead of optimising our current code.
What do you think about `smart_open` project?

**Comment by markopy** [comment] 2020-12-10 20:41
I think this is the same bug I ran into. I noticed it continuously uploading data and never finishing.

Using `smart_open` might be a good idea since it is much more widely used and tested. It does magic things though like decompression of certain file types based on extension which would need to be disabled.

**Comment by impredicative** [comment] 2020-12-10 20:49
@waiyip-aquabyte For writing small files, `s3path` seems fine as is. For writing a medium or a large file in a single step,  [`boto3` works](https://github.com/liormizr/s3path/issues/44). For streaming writing a large file, `smart_open` is best.

**Closed** 2021-05-14 04:35 UTC
